### PR TITLE
v2.17.1

### PR DESCRIPTION
**Pull request by cferdinandi**
Normalized Petfinder data when only 1 pet listing is available, fixing bug that broke the layout

### CODE REVIEW

**Comment by MikeiLL** [comment]
Nice. Good find.

**Comment by cferdinandi** [comment]
Thanks @MikeiLL! Another org that uses the theme noticed things breaking when only 1 pet was available. I cannot believe how inconsistent the Petfinder API is with the data it returns. There's so much `if/then` logic you need to use to make it work right.

**Comment by MikeiLL** [comment]
Yes. API’s can be frustrating.

I made a plugin interfacing with an API for a client and about a week after I had finished it they announced they were going to charge the developers a monthly fee for interfacing with it. Also the images they return are no larger than like 200pixels, making them useless for social shares.

**Comment by cferdinandi** [comment]
Oh boy!

**Pull request merged**
